version: "3"

services:

  monenses-postgres:
    image: 'postgres:9.6'
    container_name: monenses-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 'monenses123'
      POSTGRES_DB: 'monenses'
  
  nginx:
    image: nginx:1.13
    container_name: monenses-nginx
    restart: always
    # network_mode: host
    networks:
      - backbone
    volumes:
      - ${APPLICATION}:/usr/monenses/app
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"

  server:
    container_name: monenses-server
    networks:
      - backbone
    build:
      context: ../server
      dockerfile: Dockerfile
    expose:
      - 8010

networks:
  backbone:
    driver: bridge